flowchart LR
    subgraph B[离线数据重建]
        B1(数据按地理聚类) --> B4
        B2[单趟重建<br/>推理 / 位姿优化 / 地图优化]
        B2 --> B3(单趟地图)
        B3 --> B4[多趟语义标量重建]
        B4 --> B5(3D标量重建地图)
        B5 -- 道路矢量标注 --> B6(道路语义地图)
        B6 -- 单趟重定位 --> B8(单趟语义GT)
    end
