flowchart LR
    subgraph H[数据策划]
        C(存量-原始数据池) -- 挖掘 --> A[数据理解]
        G(流式数据管道) -- 采集 --> A[数据理解]
        E[数据合成] --> F
        F(结构化数据池) --> B[数据平衡]
        A[数据理解] --> F
    end
    B --> D[模型训练]
    D --> H
